/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_basex_fs_BaseXFS */

#ifndef _Included_org_basex_fs_BaseXFS
#define _Included_org_basex_fs_BaseXFS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_basex_fs_BaseXFS
 * Method:    j2cInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_basex_fs_BaseXFS_j2cInfo
  (JNIEnv *, jobject);

/*
 * Class:     org_basex_fs_BaseXFS
 * Method:    j2cMount
 * Signature: ([Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_basex_fs_BaseXFS_j2cMount
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
